### ISSUE TITLE
Add support for DLL module definitions.

### ISSUE THREAD

**Issue by jmgao** [jimporter/bfg9000#109]
This is needed to export functions by ordinal, which is required to maintain ABI compatibility with existing DLLs. When linking with MSVC, you pass `/DEF <foo.def>`, and with the binutils linker, it looks like you just pass it as another input file.

(This is supported under meson as `vs_module_defs`.)

**Comment by jimporter** [comment]
As a hack, you should be able to do this now for binutils like so:

```python
def_file = object_file('<path-to-dep-file>')
shared_library('blah', files=['src1.c', 'src2.c', def_file], ...)
```
