### ISSUE TITLE
Add support for removing the 'lib' prefix on libraries.

### ISSUE THREAD

**Issue by jmgao** [jimporter/bfg9000#110]
The names of Windows DLLs generally aren't prefixed with 'lib'. Meson calls this `name_prefix`.

**Comment by jimporter** [comment]
Your use case for this is building a DLL file from MinGW right? An easier solution might be to *always* remove the `lib` from MinGW-built DLLs; it's not actually clear to me if outputting `libfoo.dll` by default is the right behavior. In fact, after consulting the MinGW docs briefly, it seems that not having the `lib` prefix is the accepted way to do things: <http://www.mingw.org/wiki/sampledll>.

(Customizing the lib prefix is still something bfg should do, but I think that should be reserved for more-esoteric cases than this. This case should Just Work.)

**Comment by jmgao** [comment]
Yep. That sounds reasonable to me.
