### ISSUE TITLE
Uninstall target for GNU make

### ISSUE THREAD

**Issue by Ipsum** [jimporter/bfg9000#113]
The generated install target works great, it would be really nice if an uninstall target was also generated. The install fails if a prior install was already done (which is fine), but an uninstall target would make development iteration easier.

**Comment by jimporter** [comment]
This should be covered under #81, which is part of v0.3. Also, you should be able to run `make install` repeatedly to overwrite the old install. Is there anything else peculiar to your setup that might be affecting this?

**Comment by jimporter** [comment]
Resolving this per the comment above; if it's not working on master (though it should be working on v0.3 too), feel free to comment and I can look into it further.
