### ISSUE TITLE
Support Multiple pch files in executable.

### ISSUE THREAD

**Issue by TinfoilPancakes** [jimporter/bfg9000#118]
Currently object_file(...) and executable(...) 'pch' arg only support 1 precompiled header at a time and do not support multiple.

Is there another way to do this, or is this a limitation?

**Comment by jimporter** [comment]
Sadly, this is a compiler limitation. GCC and MSVC both only support a single precompiled header per compilation. Clang is a little more advanced and lets you chain PCH files, but that's pretty esoteric and bfg9000 doesn't support doing this.
