### ISSUE TITLE
`.d` dependency file not included in Makefile

### ISSUE THREAD

**Issue by pazner** [jimporter/bfg9000#125]
I have a simple `build.bfg` file as follows:
```
static_library('a', files='a.cpp')
executable('b', files='b.cpp')
```
I then create a Makefile for this project: `9k --backend make build`. The resulting makefile is missing an `-include` line for the dependency file `b.int/b.o.d`.

**Comment by jimporter** [comment]
Whoops, I was emitting the `-include` in the wrong spot. I should have a fix for this...

**Comment by pazner** [comment]
Thanks for the quick fix!

**Comment by jimporter** [comment]
And thanks for catching this bug! I use the ninja backend locally, so I just never noticed this (and of course the tests covering this code didn't bother to check the N>1 case).

I'll probably publish v0.5.1 in the next day or two with this fix plus patches for a couple other small issues I noticed.

**Comment by jimporter** [comment]
Ok, 0.5.1 is out with this fix on all the usual sites.
