### ISSUE TITLE
copy_file doesn't work with directories (make backend)

### ISSUE THREAD

**Issue by pazner** [jimporter/bfg9000#127]
Consider the `build.bfg` file:
```
f = copy_file("data/a.txt")
default(f)
```
The fact that `a.txt` is in a subdirectory causes `copy_file` to fail (at least with the `make` backend):
```
cp -f '/path/to/data/a.txt' 'data/a.txt'
cp: cannot create regular file ‘data/a.txt’: No such file or directory
```
Trying to force the directory to be created with something like `copy_file("data")` also does not work.

(Also, `default` does not work with the return value of `copy_files` without splatting)

**Comment by jimporter** [comment]
This is fixed in the latest master. As a workaround, you can use the Ninja or MSBuild backends on v0.5. Alternately, you could do something like this:

```python
f = copy_file("data/a.txt")
if env.backend == 'make':
    f = alias('copy-data', deps=[
        command('mkdir data', cmd=['mkdir', '-p', 'data']),
        f
    ])
```

In an ideal world, you'd be able to work around this issue with `extra_deps`, but it turns out that was broken for `copy_file()` too... :(
