### ISSUE TITLE
(Linux) Warn when running setup.py if patchelf isn't installed

### ISSUE THREAD

**Issue by jimporter** [jimporter/bfg9000#13]
Fairly self-explanatory, I think.

**Comment by nlhepler** [comment]
Actually, should we change from patchelf to chrpath? It's more universally available than patchelf, AFAICT. And since we already set rpath with `-Wl,-rpath,$ORIGIN` , we shouldn't have any difficulties.

**Comment by jimporter** [comment]
We can't. `chrpath` doesn't allow you to extend the length of the `rpath` field, so you'd only be able to install to places whose pathname was shorter than `$ORIGIN` (or you'd have to pad the initial `rpath` value, and that requires closely coupling all the rpath-related code, which I really want to avoid).

**Comment by nlhepler** [comment]
I didn't know that. That's monumentally dumb. Oh well, nevermind.

I suppose another way to do away with the patchelf dependency would be, when detecting an `install(...)` directive, to prepend the appropriate rpaths at link time rather than using patchelf to modify post-installation.

**Comment by jimporter** [comment]
That might cause problems if you're building a shared lib and an executable that uses the lib. If you've already installed a version of the project and then want to test a patch, the rpath will select the *installed* shared lib instead of the *development* shared lib.

**Comment by jimporter** [comment]
Luckily, patchelf is *really* easy to download and build, so when I fix this, I can easily add a setup.py command that fetches the tarball, and then extracts, builds, and installs it. It probably wouldn't be too hard to support installing patchelf into a virtualenv as well.

**Comment by jimporter** [comment]
@nlhepler Earlier we were discussing the relative merits of installing patchelf into the virtualenv's bin dir in #41. I talked to Python packaging guru dstufft today and he says that that is indeed the recommended way to do things. Once I finish off the last couple 0.1 issues and cut a release, I'll try to get this working so that `pip install` automatically builds and installs patchelf as necessary.
