### ISSUE TITLE
Linter errors

### ISSUE THREAD

**Issue by ompadu** [jimporter/bfg9000#139]
Is there a way to make the linter happy by importing a dummy package or something when opening `.bfg` files in an ide?

**Comment by jimporter** [comment]
Unfortunately, no not really. I think the answer here is to add an [LSP](https://langserver.org/) configuration for bfg scripts, but that's complicated and I don't fully understand how it works. There's also #136 and #135 for this issue.

**Comment by ompadu** [comment]
Oh, it's okay. Thank you for the answer :)

**Comment by jimporter** [comment]
I filed #140 to track the LSP implementation. I'd like to get something working for it for 0.7, but I haven't been able to find much information out there on how you'd make a "derived" LSP language; all I really need is a way to say "this file is in Python syntax with these extra builtin symbols", but that seems to be nontrivial (or at least no one else has tried to do this, so there's no documentation on how to do it).

**Comment by ompadu** [comment]
Maybe forking an existing python LSP, and adding the bfg stuff to it?

**Comment by jimporter** [comment]
Yeah, that's about what I'm thinking. Maybe there are even some hooks in one or another Python LSP implementation that I could use...

**Comment by ompadu** [comment]
Wouldn't it have been easier to just have bfg9000 be a ordinary python module, that we could just import in the build script and run it with python? What are the advantages of doing it like this?

**Comment by jimporter** [comment]
The main advantage is that the .bfg script evaluation is only one phase of all the work necessary to generate the Makefiles for an actual build. While it's easy enough to do stuff *before* the .bfg script when it's just a module, it's not easy to do stuff after it.
