### ISSUE TITLE
Rewrite the install command

### ISSUE THREAD

**Issue by jimporter** [jimporter/bfg9000#32]
Currently, the install command uses a variety of GNU tools (`install`, `cp -r`, and `mkdir -p`). Write a new program that does this in a simpler way so that we can just use that. Then Windows users won't need GnuWin32 CoreUtils to install stuff.

**Comment by nlhepler** [comment]
+1, because mac os x needs coreutils too, but it's typically installed under a g-prefix.

**Comment by jimporter** [comment]
Well, in the short term, I could fix that the same way I do with mkdir: https://github.com/jimporter/bfg9000/blob/master/bfg9000/tools/mkdir_p.py

**Comment by jimporter** [comment]
I'm thinking I'd like to handle this by creating a separate (Python-based) command-line utility that does everything I need. Then people can use it for other things. I'm not sure how this will interact with #31, though...
