### ISSUE TITLE
patsubst for directory_rule in make backend doesn't work

### ISSUE THREAD

**Issue by nlhepler** [jimporter/bfg9000#38]
single-quoting the $@ causes the patsubst to not match, thus we just mkdir -p $targetdir/.dir and then touch the new directory $targetdir/.dir. I think the intent was to create a 0-sized file .dir in $targetdir.

Removing the quotes breaks spaced-things, we need to use double-quotes here, but I see no easy way to do so without significant changes. Not sure how important it is.

**Comment by jimporter** [comment]
Oh, that should be easy actually! I think I just need to quote the entirety of the `patsubst` call.

**Comment by jimporter** [comment]
Fixed with tests to be sure it doesn't regress later. Make really does make it hard to use spaces in filenames...
