### ISSUE TITLE
Add copy/symlink build steps

### ISSUE THREAD

**Issue by jimporter** [jimporter/bfg9000#51]
It might be useful to add the ability to copy/link a directory, e.g. to make it easier to package up resource files. Obviously, you can already do this with `command()`, but a platform-agnostic way could be useful. One question is what to call the link function. Symlinks and hardlinks are both nice, but "link" is too confusing: it sounds more like linking an executable.

I'm not even 100% sure I'd want these steps in the first place, so I'm leaving this open to let folks discuss it. If there's a consensus in favor of this, I'll add support.

**Comment by Ipsum** [comment]
You could call it something like "fs_link" or just call it "symlink" since i'm not sure a hardlink is terribly useful in the context of this tool.

**Comment by jimporter** [comment]
@Ipsum I've started to lean towards just calling it `copy()` and having a `mode` argument that accepts `'copy'` (the default), `'symlink'`, or `'hardlink'`. I think copying is the most-common case.

Related to this would be the ability to add configuration-time overrides; one of the really useful parts of Firefox's build system is that for dev builds, you can avoid copying all the JS/HTML/CSS/etc files to the build dir and just refer to the files in the src dir. If bfg had a `copy()` function like this, you could default to real copies (which you'd want for deploying your build), but you could specify something like `--with-symlinks` during configuration to use symlinks instead during development. If you have a lot of stuff to copy over, this could speed up your dev builds quite a bit.

**Comment by jimporter** [comment]
Fixed in ce0f21710786dce6d79caee998f181c7b7808e14
