### ISSUE TITLE
Allow for easier configuration of builds

### ISSUE THREAD

**Issue by jimporter** [jimporter/bfg9000#63]
Users of bfg-based projects should be able to configure various aspects of the build. Currently, this is only possible via environment variables. bfg should allow users to supply custom command-line options to configure builds.

Progress:
* [x] Support defining options in `build.opts`
* [x] Add help output
* [x] Disable abbreviated long-option support in `ArgumentParser`
* [ ] Document everything

**Comment by jimporter** [comment]
@kirbyfan64 Since you filed #67, you might have some thoughts on this. What do you think about having a separate file that sits alongside `build.bfg` to list the command-line arguments? Something like `build.opts`, which would have a list of the arguments your build understands. Then it'd be easy to parse them before running `build.bfg` and it would be fairly straightforward to show help messages.

However, this seems a bit clumsier than letting users define their command-line args in the `build.bfg` file itself. This would be a lot more implementation effort though (mainly because I'd like to error out on unknown args *before* running the main part of `build.bfg`).

**Comment by kirbyfan64** [comment]
@jimporter Sounds fine to me. IIRC Meson does the same thing.

One option could always be to have `build.bfg` look like this:

```python
add_option(stuff)
add_option(more_stuff)
args = parse_argv()  # <-- here
# normal code here
```

**Comment by jimporter** [comment]
The problem with doing something like your sample is that I'd have to be extra-clever to handle the scenario where the `build.bfg` *never* calls `parse_argv()`. Ideally, I'd still like it to halt near the beginning if the user passes an unknown option. The best way I can think of to do that would be to walk the AST of `build.bfg` before executing it to see if `parse_argv` is called, and if not, inject it at the beginning.

It also makes it harder (but not impossible) to generate help messages; I'd have to run the script with `add_option` and `parse_argv` redefined to generate help and exit the build script.

One final question is how to ensure that user-defined arguments don't conflict with future arguments defined by bfg9000. Maybe automatically prefix all user-defined ones with "x-" (e.g. "--foo" becomes "--x-foo")? Or do something like "-X foo"...

I guess I'll have to think about this some more.

**Comment by jimporter** [comment]
Another way would be that all arguments defined by bfg have to come *before* the directory name, and all user-defined arguments come after. For instance, this wouldn't be allowed:

```sh
9k builddir --backend=make
```

And you'd have to type this instead:

```sh
9k --backend=make builddir
```

That might be too confusing...
