### ISSUE TITLE
Support finding Java packages

### ISSUE THREAD

**Issue by jimporter** [jimporter/bfg9000#71]
I don't know much about Java packages, where they go, etc, but there are surely some standards here. We should support them in some sensible way. Should `system_package` be able to pick up Java packages, or should that be just for native-code packages?

**Comment by kirbyfan64** [comment]
http://stackoverflow.com/a/20759895/2097780

**Comment by jimporter** [comment]
Hm, that does raise an interesting question: should the Java toolchain have a concept of shared vs static libs? Shared libs could be external .jar files referenced by Class-Path (which is what I do currently), whereas static libs could just get crammed in the .jar that "links" to it. This is a bit different from native code, where the shared/static distinction happens when you build the lib; this would happen when you *use* the lib. Not sure how I'd indicate that in the build.bfg files.

Also worth considering: should executable .jar files (ones with a Main-Class) be usable as libraries?

**Comment by kirbyfan64** [comment]
All I know is that I started learning Java, then I stopped because I value my sanity.

**Comment by jimporter** [comment]
Yeah, ultimately all this is more for Scala than Java, since I've heard nothing but complaints about sbt (Scala Build Tool). Luckily the two work almost identically, but I hope I can eventually find knowledgeable Scala/Java people to show me the best practices here or even better, to actually maintain this part of the code.

**Comment by jimporter** [comment]
There's `java.ext.dirs`, which would be a good place to look for Java packages. You can get that value either by `System.getProperty()` or `-XshowSettings:properties` on the command line. That plus some env var like `CLASSPATH` (or something else) should be enough for an initial version.
