### ISSUE TITLE
Support installing Java binaries

### ISSUE THREAD

**Issue by jimporter** [jimporter/bfg9000#72]
Right now, Java binaries will probably get installed in weird places that break things. Fix this (once I figure out where they're supposed to go).

**Comment by kirbyfan64** [comment]
They kinda don't go anywhere. AFAIK, since all Java programs are just libraries with a main function, the "binary" jar gets installed like a library, and a shell script in `/usr/bin` calls the JVM to run it.

**Comment by jimporter** [comment]
Well, right now they get installed like native programs, so "executables" go in `/usr/local/bin` and libraries go in `/usr/local/lib`, but that messes up the relative Class-Paths for linking to libs built alongside the executable (Class-Paths currently assume that everything is in the same root dir). In the end, they'll probably go in the same dir, but I haven't decided how to do that.

Or, as an alternative, I could do the same thing `patchelf` does and modify the Class-Paths during the installation step.
