### ISSUE TITLE
lxml packaged required for OS X

### ISSUE THREAD

**Issue by Hamled** [jimporter/bfg9000#76]
Because `list_backends()` (called by `main()` and `simple_main()`) is implemented via dynamically loading all modules in the `backends/` directory when BFG9000 starts, the MSBuild backend is always loaded.

However the lxml dependency is only added in the setuptools script if the msbuild option is specified, resulting in a crash when either the `bfg9000` or `9k` commands are used if lxml is not installed on already.

I looked into this briefly and it doesn't seem like the architecture of the project is setup to easily "disable" the MSBuild backend should lxml not be installed. The simplest solution is probably to make lxml a dependency across the board.

Repro steps:
```bash
$ pip install bfg9000 # if not already installed
$ pip uninstall lxml
$ 9k
```

**Comment by jimporter** [comment]
I've had a couple people report this on OS X and I cannot for the life of me figure out why it's happening. On Linux, `lxml` isn't required at all (unless you specifically want to use MSBuild) and everything works fine. I believe it works on Windows too (with the same caveat), but I don't think I have an automated test to check that. I should add one.

**Comment by jimporter** [comment]
The other weird thing is that this only happens when you install from PyPI, not from a source checkout. I haven't touched the backend loader since I released 0.2, so I don't think it's something I changed in bfg. Under all other circumstances, the MSBuild backend is correctly disabled when you don't have lxml.

**Comment by jimporter** [comment]
Ok, I've managed to reproduce this on Travis by creating an sdist first and `pip install`ing that: <https://travis-ci.org/jimporter/bfg9000/jobs/183069175>. I'll see if I can narrow down where the bug is now.

**Comment by jimporter** [comment]
It turns out this is caused by installing bfg9000 as a Wheel. I've filed an issue with setuptools here: https://github.com/pypa/setuptools/issues/882
