### ISSUE TITLE
Name 'package' is not defined

### ISSUE THREAD

**Issue by max-kamps** [jimporter/bfg9000#91]
Trying to configure my project gives me this error:
```
error: build.bfg:3: name 'package' is not defined
  File "build.bfg", line 3, in <module>
    glfw = package('glfw', version='>=3.2.1')
```

Here is my build file in case it helps:
```py
project('proglyn', version='0.0.1')

glfw = package('glfw', version='>=3.2.1')
pthread = package('pthread')

executable(
    'proglyn',
    compile_options=['-Ofast -flto'],
    includes=['3rdparty/include', '3rdparty/include/nanovg'],
    files=['src/main.c', '3rdparty/src/glad.c', '3rdparty/src/nanovg.c'],
    packages=[glfw, pthread])```

**Comment by jimporter** [comment]
Sorry, you'll need the master version of bfg to use `package`. The docs are for the master version, not the latest release on PyPI. :(

On the plus side, I do plan on releasing the next version of bfg soon (hopefully mid-October when my day job has slowed down a bit), and I'm also looking at fixing mkdocs/mkdocs#193 so I can serve multiple versions of my docs to prevent this kind of confusion in the future.

**Comment by max-kamps** [comment]
Oh, well thank you for that insanely fast reply. 😄 Really loving this program! Great work!

**Comment by jimporter** [comment]
Thanks for the kind words! The current master is pretty stable, so if you want to use it for your project, feel free. (It's almost release-ready; I just have a couple minor features to add.)

**Comment by jimporter** [comment]
Ok, I've set up the docs so that when the next version is released (I've learned not to make any promises about when, but there are only a few things left to do), the docs page will default to the latest *released* version. That should eliminate the confusion that caused this issue.
